### ISSUE TITLE
Attester Identity

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#10]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Attester Identity:  The provenance of Evidence with respect to a
> distinguishable Attesting Environment MUST be correct and
> unambiguous.

The Attester Identity is to identify which Attester the Evidence comes from. But if the Attester has multiple Attesting Environments, what should be the Attester Identity?

**Comment by henkbirkholz** [comment]
The TPM’s AIK certificate is one kind of Attester Identity, right?

**Comment by eckelmeckel** [comment]
"The TPM’s AIK certificate is one kind of Attester Identity, right?": Correct.

**Comment by eckelmeckel** [comment]
"The Attester Identity is to identify which Attester the Evidence comes from. But if the Attester has multiple Attesting Environments, what should be the Attester Identity?" I see the point, too, and agree. So, perhaps it should be renamed to "Attesting Environment identity"!? The Attester Identity then should be something different. It may be the TPM AK/AIK of one of the Attesting Environments, but not necessarily.
