### ISSUE TITLE
Correct Evidence

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#11]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Attestation Evidence Authenticity:  Attestation Evidence MUST be
> correct and authentic.

Is it appropriate to say “correct Evidence”? If saying so, I think it means that the Evidence satisfies the Attestation Policy for Evidence.

**Comment by eckelmeckel** [comment]
"I think it means that the Evidence satisfies the Attestation Policy for Evidence.": I agree. So, perhaps it is the best to just remove the words "corrent and ", because this is about authenticity and not at all related to correctness.

Correct me if I am wrong.
