### ISSUE TITLE
What in an Attester is acutally identified and how?

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#13]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Attester Identity ('attesterIdentity'):  _mandatory_
> A statement about a distinguishable Attester made by an Endorser
> without accompanying evidence about its validity - used as proof
> of identity.

Previous section says “Attester Identity” is about “a distinguishable Attesting Environment”, and here says it’s about “a distinguishable Attester”.

**Comment by henkbirkholz** [comment]
How to understand “without accompanying evidence about its validity”?

**Comment by eckelmeckel** [comment]
> How to understand “without accompanying evidence about its validity”?

I think it means that there is no certificate conveyed along with it which proves its validity.

**Comment by eckelmeckel** [comment]
> Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/
> 
> > Attester Identity ('attesterIdentity'):  _mandatory_
> > A statement about a distinguishable Attester made by an Endorser
> > without accompanying evidence about its validity - used as proof
> > of identity.
> 
> Previous section says “Attester Identity” is about “a distinguishable Attesting Environment”, and here says it’s about “a distinguishable Attester”.

I think this is related to #10 and should be fixed.
