### ISSUE TITLE
Authentication Secret ID

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#15]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Authentication Secret IDs ('authSecID'):  _mandatory_
> A statement representing an identifier list that MUST be
> associated with corresponding Authentication Secrets used to
> protect Evidence.

Previous section says “Authentication Secret” is used to protect Claims, but here says it’s used to protect Evidence.

**Comment by henkbirkholz** [comment]
As I understand, if Authentication Secret represents the identity of Attesting Environment, then it’s not mandatory, at least in our implementation.

**Comment by eckelmeckel** [comment]
TL;DR: “Authentication Secret” protects evidence (i.e. a TPM Quote) and must be *mandatory*.

Please also have a look at my comment https://github.com/ietf-rats-wg/draft-ietf-rats-reference-interaction-models/issues/12#issuecomment-810613988.

Feel free to correct me. :-)
