### ISSUE TITLE
Reference Claims vs Reference Values

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#17]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Reference Claims ('refClaims')  _mandatory_
> Reference Claims are components of Reference Values as defined in
> [I-D.ietf-rats-architecture].  [Editor's Note: Definition might
> become obsolete, if replaced by Reference Values.  Is there a
> difference between Claims and Values here?  Analogously, why is
> not named Reference Claims in the RATS arch?]

I suggest using Reference Values to keep consistent with the RATS arch.

**Comment by eckelmeckel** [comment]
+1 for "Reference Values"

**Comment by henkbirkholz** [comment]
on it
