### ISSUE TITLE
Application of Reference Values

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#18]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Reference Claims are used to appraise the Claims received from an
> Attester via appraisal by direct comparison.

“Direct comparison” isn’t the correct expression, the comparison can have other rules.

**Comment by eckelmeckel** [comment]
I agree. So, we should remove the words "via appraisal by direct comparison."
