### ISSUE TITLE
Scope of Claims Set in Claims Selection

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#19]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Claim Selection ('claimSelection'):  _optional_
> A statement that represents a (sub-)set of Claims that can be
> created by an Attester.
> Claim Selections can act as filters that can specify the exact set
> of Claims to be included in Evidence.  An Attester MAY decide
> whether or not to provide all Claims as requested via a Claim
> Selection.

The “all Claims” may be ambiguous, I’d like to double check, does it refer to all Claims that the Attester can create or refer to all Claims requested in the Claim Selection?

**Comment by eckelmeckel** [comment]
If understand correctly, the message here is that an Attester can decide to provide less Claims than specified in the Claims Selection, which appears viable to me and is used in practice, too. I will adapt the text accordingly.
