### ISSUE TITLE
A few definitions are missing for Challenge/Response Remote Attestation

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#20]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

In the sequence diagram, some elements in the bracket are not defined in the “Information Elements” section, such as targetEnvironment, collectedClaims, eventLog. Should these elements be defined?

**Comment by eckelmeckel** [comment]
I totally agree. These elements should either be put into Information elements (preferred), or at least be mentioned in the text.
