### ISSUE TITLE
Collapsed Endorser role and DAA Issuer role

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#6]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> In order to enable the use of DAA, an Endorser role takes on the
> duties of a DAA Issuer in addition to its already defined duties.
> DAA Issuers offer zero-knowledge proofs based on public key
> certificates used for a group of Attesters [DAA].  Effectively, these
> certificates share the semantics of Endorsements, with the following
> exceptions:

In the first sentence, I suggest saying that “a DAA Issuer takes on the role of an Endorser”.

**Comment by Liqun-Chen** [comment]
We agree that it is more accurate to say that the DAA Issuer takes on the role of an Endorser. We note that the DAA Issuer and the Endorser could be two separate entities.

**Comment by henkbirkholz** [comment]
resolved in draft-birkholz-rats-daa
