### ISSUE TITLE
Validity of Evidence

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#7]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> The associated private keys are used by the DAA Issuer to provide
> an Attester with a credential that it can use to convince the
> Verifier that its Evidence is valid.  To keep their anonymity the
> Attester randomizes this credential each time that it is used.

How to understand “Evidence is valid”? Does it mean the Evidence is sent from an authentic Attester and not tampered during the conveyance? Or does it mean the Evidence comes from a RoT and is trustable (although the Evidence can diverge from the Reference Values)?

**Comment by henkbirkholz** [comment]
When saying “Attester randomizes this credential”, how many credentials does an Attester have? 1) Can a DAA Issuer have multiple key pairs and use them for one Attester? 2) Can a DAA Issuer use one key pair to generate multiple credentials for one Attester?

**Comment by eckelmeckel** [comment]
This issue seems to have vanished into thin air in the course of the refactoring.
