### ISSUE TITLE
Conveyance of pub-keys

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#8]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> A credential is conveyed from an Endorser to an Attester in
> combination with the conveyance of the public key certificates
> from Endorser to Verifier.

Is there another way to convey the public key certificate, for example, can the public key certificates be conveyed from Endorser to Attester first and then from Attester to Verifier?

**Comment by eckelmeckel** [comment]
TL;DR: I think that is a valid conveyance method.

In general, I think it does not matter. At the end, the correct public key must be available to the entity which verifies signed evidence. The public key can be part of a certificate, but can be stored in a verifier during production, too (and many many other ways are thinkable).

How the key is distributed? There are also no limits to this. On a USB pendrive via airmail ... why not? (It would even provide air gap support).

Feel free to correct me.

**Comment by henkbirkholz** [comment]
moved to draft-birkholz-rats-daa

**Comment by eckelmeckel** [comment]
This issue seems to have vanished into thin air in the course of the DAA refactoring. So, it can be closed.
