### ISSUE TITLE
Definition of DAA duties

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#9]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> The zero-knowledge proofs required cannot be created by an Attester
> alone - like the Endorsements of RoTs - and have to be created by a
> trustable third entity - like an Endorser.  Due to that semantic
> overlap, the Endorser role is augmented via the definition of DAA
> duties as defined below.  This augmentation enables the Endorser to
> convey trustable third party statements both to Verifier roles and
> Attester roles.

For “the definition of DAA duties as defined below”, what is the definition of DAA duties?

**Comment by henkbirkholz** [comment]
In the last sentence, the Endorsement with its original definition is the third party statement for Verifier and Attester, isn’t it? So, “augmentation” isn’t the correct expression.

**Comment by Liqun-Chen** [comment]
"the definition of DAA duties" should be "the definition of the DAA Issuer's duties". The DAA Issuer's duty is to provide the attester with a DAA credential.

The last sentence could be omitted.

**Comment by henkbirkholz** [comment]
resolved in draft-birkholz-rats-daa
